import { Doctor } from './../../models/doctor';
import { Injectable } from '@angular/core';
import { Observable, throwError } from 'rxjs';
import { userModel } from '../../models/userInfoResponseModel';

import { HttpClient, HttpHeaders, HttpParams  } from '@angular/common/http';
import 'rxjs/add/operator/catch';

import { environment } from '../../environments/environment';
import { ClinicalHistory } from '../../models/clinicalHistory';

const API_URL = environment.apiURL;
const GET_PENDING = '/pendingclients';
const CHANGE_STATUS = '/change-client-status/';
const ADULT_HISTORY = '/clinicHistory/';
const ADULT = '/adult/';
const CLIENT_HISTORIES = '/clinicHistories';
const ALL_DOCTORS = '/doctors';


@Injectable({
  providedIn: 'root'
})
export class GetInfoService  {
/**
    * Constructor of the service
    * @param http The HttpClient - This is necessary in order to perform requests
    */
   constructor(private http: HttpClient) { }

  getPendingUsers(): Observable<userModel[]> {
    const httpOptions = {
      headers: new HttpHeaders({
      })};
    return this.http.get<userModel[]>(API_URL + GET_PENDING, httpOptions);
  }

  getClinicHistories(): Observable<ClinicalHistory[]> {
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'
      })};
    return this.http.get<ClinicalHistory[]>(API_URL + CLIENT_HISTORIES, httpOptions);
  }

  changeStatus(id, status): Observable<userModel> {
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'
      })};
      const body = new HttpParams()
      .set('status', status);
      console.log("Cambiando " + id + " " + status);
    return this.http.put<userModel>(API_URL + CHANGE_STATUS + id, body, httpOptions);
  }

  adultClinicHistory(id): Observable<ClinicalHistory> {
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'
      })};
    return this.http.get<ClinicalHistory>(API_URL + ADULT_HISTORY + id, httpOptions);
  }

  getAdult(id): Observable<userModel> {
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'
      })};
    return this.http.get<userModel>(API_URL + ADULT + id, httpOptions);
  }

  getAllDoctors(): Observable<userModel[]> {
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'
      })};
    return this.http.get<userModel[]>(API_URL + ALL_DOCTORS, httpOptions);
  }


    /**
     * The method which handles the errors generated by the requests
     * @param error The error which the API REST returned
     */
    private handleError(error: any) { 
        return throwError(error.error.errorMessage);
    }
}