import { Injectable } from '@angular/core';
import { Observable, throwError } from 'rxjs';
import { userModel } from '../../models/userInfoResponseModel';

import { HttpClient, HttpHeaders, HttpParams  } from '@angular/common/http';
import 'rxjs/add/operator/catch';

import { environment } from '../../environments/environment';
const API_URL = environment.apiURL;
const API_DOCTOR_REG = '/doctors';


@Injectable({
  providedIn: 'root'
})
export class RegisterService {
/**
    * Constructor of the service
    * @param http The HttpClient - This is necessary in order to perform requests
    */
   constructor(private http: HttpClient) { }

   /**
    * returns JWT for the given credentials
    * @returns The list of authors in real time
    */
   postUserReg(user): Observable<userModel> {
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'
      })};
      const body = new HttpParams()
      .set('email', user.email)
      .set('password', user.password.pwd)
      .set('firstName', user.firstName)
      .set('lastName', user.lastName)
      .set('birthDate', user.dateOfBirth)
      .set('RH', "O+");
      return this.http.post<userModel>(API_URL + API_DOCTOR_REG,body, httpOptions);
  }

    /**
     * The method which handles the errors generated by the requests
     * @param error The error which the API REST returned
     */
    private handleError(error: any) { 
        return throwError(error.error.errorMessage);
    }
}

