import { Injectable } from '@angular/core';
import { Observable, throwError } from 'rxjs';
import { userModel } from '../../models/userInfoResponseModel';
import { ClinicalHistory } from '../../models/clinicalHistory';

import { HttpClient, HttpHeaders, HttpParams  } from '@angular/common/http';
import 'rxjs/add/operator/catch';

import { environment } from '../../environments/environment';
import { NewService } from '../../models/serviceModel';
const API_URL = environment.apiURL;
const API_DOCTOR_REG = '/doctors';
const API_ADULT_REG = '/adult';
const API_SERV_REG = '/companionService';
const API_NURSE_REG = '/nurses';
const API_HISTORIES_REG = '/clinicHistory';

@Injectable({
  providedIn: 'root'
})
export class RegisterService {
/**
    * Constructor of the service
    * @param http The HttpClient - This is necessary in order to perform requests
    */
   constructor(private http: HttpClient) { }

   postDocReg(user): Observable<userModel> {
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'
      })};
      const body = new HttpParams()
      .set('email', user.email)
      .set('password', user.password.pwd)
      .set('firstName', user.firstName)
      .set('lastName', user.lastName)
      .set('birthDate', user.dateOfBirth)
      .set('RH', "A+");
      return this.http.post<userModel>(API_URL + API_DOCTOR_REG,body, httpOptions);
  }

  postAdultReg(user): Observable<userModel> {
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'
      })};
      const body = new HttpParams()
      .set('email', user.email)
      .set('password', user.password.pwd)
      .set('firstName', user.firstName)
      .set('lastName', user.lastName)
      .set('birthDate', user.dateOfBirth)
      .set('RH', "A+");
      return this.http.post<userModel>(API_URL + API_ADULT_REG,body, httpOptions);
  }

  postServReg(service): Observable<NewService> {
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'
      })};
      const body = new HttpParams()
      .set('startDate', service.startDate)
      .set('endDate', service.endDate)
      .set('type', service.type)
      .set('description', service.description)
      .set('price', service.price)
      .set('adultEvaluation', '-1')
      .set('nurseEvaluation', '-1')
      .set('adultId', service.adultId)
      .set('nurseId', service.nurseId);
      return this.http.post<NewService>(API_URL + API_SERV_REG,body, httpOptions);
  }

  postNurseReg(user): Observable<userModel> {
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'
      })};
      const body = new HttpParams()
      .set('email', user.email)
      .set('password', user.password.pwd)
      .set('firstName', user.firstName)
      .set('lastName', user.lastName)
      .set('birthDate', user.dateOfBirth)
      .set('RH', "A+");
      return this.http.post<userModel>(API_URL + API_NURSE_REG,body, httpOptions);
  }

  postHistotiesReg(history): Observable<ClinicalHistory> {
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'
      })};
      const body = new HttpParams()
      .set('interviewDate', history.interview_date)
      .set('regularDoctorName', history.regular_doctor_name)
      .set('regularDoctorPhone', history.regular_doctor_phone)
      .set('actualDiagnosis', history.actual_diagnossis)
      .set('weight', history.weight)
      .set('height', "80")
      .set('pulse', history.pulse)
      .set('heartRate', history.heart_rate)
      .set('temperature', history.temperature)
      .set('observations', history.observations)
      .set('allergies', history.allergies)
      .set('coronaryProblems',history.coronary_problems)
      .set('medicalPrecedings', history.medical_precedings)
      .set('adultId', history.adultId)
      .set('doctorId', history.doctorId);
      return this.http.post<ClinicalHistory>(API_URL + API_HISTORIES_REG,body, httpOptions);
  }

    /**
     * The method which handles the errors generated by the requests
     * @param error The error which the API REST returned
     */
    private handleError(error: any) { 
        return throwError(error.error.errorMessage);
    }
}

