import { Injectable } from '@angular/core';
import { Observable, throwError } from 'rxjs';
import { AuthResponseModel } from './authResponseModel';
import { userInfoResponseModel } from './userInfoResponseModel';

import { HttpClient, HttpHeaders, HttpParams  } from '@angular/common/http';
import 'rxjs/add/operator/catch';

import { environment } from '../../environments/environment';
const API_URL = environment.apiURL;
const auth = '/login';
const info = '/me';


@Injectable({
  providedIn: 'root'
})
export class SignInServiceService {
/**
    * Constructor of the service
    * @param http The HttpClient - This is necessary in order to perform requests
    */
   constructor(private http: HttpClient) { }

   /**
    * returns JWT for the given credentials
    * @returns The list of authors in real time
    */
   postAuth(user): Observable<AuthResponseModel> {
    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/x-www-form-urlencoded'
      })};
      const body = new HttpParams()
      .set('name', user.email)
      .set('password', user.password);
    return this.http.post<AuthResponseModel>(API_URL + auth,body, httpOptions);
  }

  getInfo(token): Observable<userInfoResponseModel> {
    const httpOptions = {
      headers: new HttpHeaders({
        'x-access-token':  token
      })};
    return this.http.get<userInfoResponseModel>(API_URL + info, httpOptions);
  }

    /**
     * The method which handles the errors generated by the requests
     * @param error The error which the API REST returned
     */
    private handleError(error: any) { 
        return throwError(error.error.errorMessage);
    }
}

